version: "3.8"
services:
  ml-service:
    build: ./ml-service
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1

  backend-node:
    build: ./backend-node
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/stocks
      - REDIS_URL=redis://redis:6379
      - ML_SERVICE_URL=http://ml-service:8000
      - PORT=5000
    depends_on:
      - ml-service
      - mongo
      - redis

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    command: ["redis-server", "--save", "60", "1"]

volumes:
  mongo-data:
